### ISSUE TITLE
Creación del DER

### ISSUE THREAD

**Issue by FernandoStreet** [classroomEntreRios/proyecto-g2a-proyecto-g2a#1]
creación del DER del proyecto VOY de atractivos turísticos de la provincia de Entre Ríos

**Comment by FernandoStreet** [comment]
![image](https://user-images.githubusercontent.com/74481346/107426557-25e68080-6aff-11eb-855b-f3b409e1e4f9.png)

**Comment by FernandoStreet** [comment]
falta la ultima modificación, con el cambio en el foro

**Comment by javihuel** [comment]
![image](https://user-images.githubusercontent.com/74661587/107428989-27657800-6b02-11eb-93e7-a37224bca0e8.png)

En esta versión están las modificaciones que charlamos, menos la del foro

**Comment by javihuel** [comment]
Observen que para Servicios agregue TipodeServicio, así el Administrador fija los tipos, y al cargarse solo se seleccionan de los que ya están predefinidos, como Hoteleria y Alojamiento, Gastronomia, Regionales, etc. Si les parece queda, sino lo quitamos

**Comment by javihuel** [comment]
![image](https://user-images.githubusercontent.com/74661587/107429647-e9b51f00-6b02-11eb-82de-419858701ed7.png)

Esta seria la versión final al día de hoy, con los cambios en el foro, solo queda TAG para agrupar comentarios del foro

**Comment by FernandoStreet** [comment]
Para mi esta bien Aldo.

**Comment by javihuel** [comment]
![image](https://user-images.githubusercontent.com/74661587/107581326-aa580280-6bd6-11eb-9a85-86d1cdf21810.png)

Este DER tiene las modificaciones en los nombres de atributos del SCRIPT
