### ISSUE TITLE
creacion del script para la bases datos

### ISSUE THREAD

**Issue by FernandoStreet** [classroomEntreRios/proyecto-g2a-proyecto-g2a#2]
Creación del script de la base de datos en función del DER y el diagrama de clases

**Comment by javihuel** [comment]
--SCRIPT DE LA BASE DE DATOS DE ACUERDO A LA ULTIMA VERSION DEL DER

--BASE DE DATOS PROYECTO VOY - GRUPO 2A - VERSION 1
--Confirmar tipos de datos

--Creamos la BD
create database BD_Voy
--La ponemos en uso
use BD_Voy

--Creamos la tabla Usuarios
CREATE TABLE Usuarios (
IdUs INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Nick NVARCHAR(40) NOT NULL,
Contraseña VARCHAR(40) NOT NULL,
Tipo INT NOT NULL,
email VARCHAR(20)
--constraint pk_us primary key (IdUs)
);
--Decidir como vamos manejar el tipo de usuario, un numero 1-Adm 2-Reg 0-Visitante?

----Creamos la tabla Ciudades
CREATE TABLE Ciudades (
IdCiudad INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Ciudad NVARCHAR(50) NOT NULL,
CP INT NOT NULL
);

--Creamos la Tabla con Atractivos Turisticos
CREATE TABLE Atractivos (
IdAtractivo INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomAt NVARCHAR(50) NOT NULL,
Descripcion NVARCHAR(300),
IdCiudad INT,
constraint fk_fCiudad foreign key(IdCiudad) references Ciudades(IdCiudad)
);

--Creamos la Tabla de RegistroClimatico
CREATE TABLE RegClima(
IdRegClima INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiudad INT,
Fecha DATETIME,
TempMax INT,
TempMin INT,
Estado VARCHAR(20),
VientoMax INT,
constraint fk_fCiudadR foreign key(IdCiudad) references Ciudades(IdCiudad)
);

--Creamos la Tabla Tipo de Servicio
CREATE TABLE TipoServ(
IdTipoServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Tipo varchar(50)
);

--Creamos la Tabla Servicios
CREATE TABLE Servicios(
IdServicio INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiudad INT,
Nombre nvarchar(50),
Descripcion varchar(200),
IdTipoServ INT,
Tel bigint,
emailServ nvarchar(50),
constraint fk_fCiudadS foreign key(IdCiudad) references Ciudades(IdCiudad),
constraint fk_fTServ foreign key(IdTipoServ) references TipoServ(IdTipoServ)
);

--Creamos la Tabla Fotos de Servicios
CREATE TABLE FotoS(
IdFoto INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFoto varchar(20),
IdServ INT,
ruta nvarchar(50),
constraint fk_fIdServ foreign key(IdServ) references Servicios(IdServicio)
);

--Creamos la Tabla Fotos de Atractivos
CREATE TABLE FotoA(
IdFoto INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFoto varchar(20),
IdAtractivo INT,
ruta nvarchar(50),
constraint fk_fAtrac foreign key(IdAtractivo) references Atractivos(IdAtractivo)
);


--Creamos la Tabla Intermedia entre Usuarios y Atractivos
CREATE TABLE UsuAtract(
IdUsuario INT,
IdAtractivo INT,
fecha DATETIME,
constraint fk_fUs foreign key(IdUsuario) references Usuarios(IdUs),
constraint fk_fAt foreign key(IdAtractivo) references Atractivos(IdAtractivo)
);

--Creamos la Tabla Posteos, para registrar los comentarios del foro
CREATE TABLE Posteos(
IdPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUsuario INT,
--IdTitulo INT,
--IdTema INT,
Tag varchar(30),
fecha DATETIME,
Comentario nvarchar(300) NOT NULL,
constraint fk_Us foreign key(IdUsuario) references Usuarios(IdUs)
);

**Comment by javihuel** [comment]
![image](https://user-images.githubusercontent.com/74661587/107475280-a1255200-6b52-11eb-8269-89c3823f5642.png)

El diagrama de Base de Datos generado a partir del Script anterior. A revisar y confirmar

**Comment by javihuel** [comment]
--BASE DE DATOS PROYECTO VOY - GRUPO 2A - VERSION 1
--Creamos la BD
create database BD_Voy
--La ponemos en uso
use BD_Voy

--Creamos la tabla Usuarios
CREATE TABLE Usuarios (
IdUs INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Nick NVARCHAR(40) NOT NULL,
ContUs VARCHAR(40) NOT NULL,
TipoUs INT NOT NULL,
emailUs VARCHAR(20)
--constraint pk_us primary key (IdUs)
);
--Decidir como vamos manejar el tipo de usuario, un numero 1-Adm 2-Reg 0-Visitante?

----Creamos la tabla Ciudades
CREATE TABLE Ciudades (
IdCiu INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomCiu NVARCHAR(50) NOT NULL,
CP INT NOT NULL
);

--Creamos la Tabla con Atractivos Turisticos
CREATE TABLE Atractivos (
IdAt INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomAt NVARCHAR(50) NOT NULL,
DescrAt NVARCHAR(300),
IdCiuAt INT,
constraint fkCiuAt foreign key(IdCiuAt) references Ciudades(IdCiu)
);

--Creamos la Tabla de RegistroClimatico
CREATE TABLE RegClima(
IdRegClima INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuReg INT,
FechaReg DATETIME,
TempMax SMALLINT,
TempMin SMALLINT,
Estado VARCHAR(20),
VientoMax INT,
constraint fkCiuReg foreign key(IdCiuReg) references Ciudades(IdCiu)
);

--Creamos la Tabla Tipo de Servicio
CREATE TABLE TipoServ(
IdTipoServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TipoS varchar(50)
);

--Creamos la Tabla Servicios
CREATE TABLE Servicios(
IdServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuS INT,
NomServ nvarchar(50),
DescrS varchar(200),
IdTipoServ INT,
TelS bigint,
emailS nvarchar(50),
constraint fkCiuS foreign key(IdCiuS) references Ciudades(IdCiu),
constraint fkTServS foreign key(IdTipoServ) references TipoServ(IdTipoServ)
);

--Creamos la Tabla Fotos de Servicios
CREATE TABLE FotoS(
IdFotoS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoS varchar(20),
IdServFS INT,
RutaFS nvarchar(50),
constraint fkIdServFS foreign key(IdServFS) references Servicios(IdServ)
);

--Creamos la Tabla Fotos de Atractivos
CREATE TABLE FotoA(
IdFotoA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoA varchar(20),
IdAtFA INT,
RutaFA nvarchar(50),
constraint fkAtFA foreign key(IdAtFA) references Atractivos(IdAt)
);


--Creamos la Tabla Intermedia entre Usuarios y Atractivos
CREATE TABLE UsAt(
IdUsUA INT,
IdAtUA INT,
FechaUA DATETIME,
constraint fkUsUsAt foreign key(IdUsUA) references Usuarios(IdUs),
constraint fkAtUsAt foreign key(IdAtUA) references Atractivos(IdAt)
);

--Creamos la Tabla Posteos, para registrar los comentarios del foro
CREATE TABLE Posteos(
IdPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUsPo INT,
--IdTitulo INT,
--IdTema INT,
Tag varchar(30),
FechaPo DATETIME,
Comentario nvarchar(300) NOT NULL,
constraint fkUsPo foreign key(IdUsPo) references Usuarios(IdUs),
);

**Comment by javihuel** [comment]
En el siguiente Script modifique los nombres según los comentarios de esta mañana.

--BASE DE DATOS PROYECTO VOY - GRUPO 2A - VERSION 2
--Creamos la BD
create database BD_Voy
--La ponemos en uso
use BD_Voy

--Creamos la tabla Usuarios
CREATE TABLE Usuarios (
IdUs INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Nick NVARCHAR(40) NOT NULL,
ContUs VARCHAR(40) NOT NULL,
TipoUs INT NOT NULL,
emailUs VARCHAR(20)
--constraint pk_us primary key (IdUs)
);
--Decidir como vamos manejar el tipo de usuario, un numero 1-Adm 2-Reg 0-Visitante?

----Creamos la tabla Ciudades
CREATE TABLE Ciudades (
IdCiu INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomCiu NVARCHAR(50) NOT NULL,
CP INT NOT NULL
);

--Creamos la Tabla con Atractivos Turisticos
CREATE TABLE Atractivos (
IdAt INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomAt NVARCHAR(50) NOT NULL,
DescrAt NVARCHAR(300),
IdCiuAt INT,
constraint fkCiuAt foreign key(IdCiuAt) references Ciudades(IdCiu)
);

--Creamos la Tabla de RegistroClimatico
CREATE TABLE RegClima(
IdRegClima INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuReg INT,
FechaReg DATETIME,
TempMax SMALLINT,
TempMin SMALLINT,
Estado VARCHAR(20),
VientoMax INT,
constraint fkCiuReg foreign key(IdCiuReg) references Ciudades(IdCiu)
);

--Creamos la Tabla Tipo de Servicio
CREATE TABLE TipoServ(
IdTipoServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TipoS varchar(50)
);

--Creamos la Tabla Servicios
CREATE TABLE Servicios(
IdServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuS INT,
NomServ nvarchar(50),
DescrS varchar(200),
IdTipoServ INT,
TelS bigint,
emailS nvarchar(50),
constraint fkCiuS foreign key(IdCiuS) references Ciudades(IdCiu),
constraint fkTServS foreign key(IdTipoServ) references TipoServ(IdTipoServ)
);

--Creamos la Tabla Fotos de Servicios
CREATE TABLE FotoS(
IdFotoS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoS varchar(20),
IdServFS INT,
RutaFS nvarchar(50),
constraint fkIdServFS foreign key(IdServFS) references Servicios(IdServ)
);

--Creamos la Tabla Fotos de Atractivos
CREATE TABLE FotoA(
IdFotoA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoA varchar(20),
IdAtFA INT,
RutaFA nvarchar(50),
constraint fkAtFA foreign key(IdAtFA) references Atractivos(IdAt)
);


--Creamos la Tabla Intermedia entre Usuarios y Atractivos
CREATE TABLE UsAt(
IdUsUA INT,
IdAtUA INT,
FechaUA DATETIME,
constraint fkUsUsAt foreign key(IdUsUA) references Usuarios(IdUs),
constraint fkAtUsAt foreign key(IdAtUA) references Atractivos(IdAt)
);

--Creamos la Tabla Posteos, para registrar los comentarios del foro
CREATE TABLE Posteos(
IdPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUsPo INT,
--IdTitulo INT,
--IdTema INT,
Tag varchar(30),
FechaPo DATETIME,
Comentario nvarchar(300) NOT NULL,
constraint fkUsPo foreign key(IdUsPo) references Usuarios(IdUs),
);

**Comment by FernandoStreet** [comment]
Excelente !! propongo que cada uno la cree en su PC , y la vaya probando

**Comment by saon** [comment]
Buena propuesta Fernando, porque el script anterior falla al ejecutarlo en SSMS18. Tiene un error muy pequeño, pero que lo inhabilita completamente.
La versión que pego debajo funciona sin inconvenientes:

/*BASE DE DATOS PROYECTO VOY - GRUPO 2A - VERSION 3
Creamos la BD*/
create database BD_Voy;
GO
--La ponemos en uso
use BD_Voy

--Creamos la tabla Usuarios
CREATE TABLE Usuarios (
IdUs INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Nick NVARCHAR(40) NOT NULL,
ContUs VARCHAR(40) NOT NULL,
TipoUs INT NOT NULL,
emailUs VARCHAR(20)
--constraint pk_us primary key (IdUs)
);
--Decidir como vamos manejar el tipo de usuario, un numero 1-Adm 2-Reg 0-Visitante?

----Creamos la tabla Ciudades
CREATE TABLE Ciudades (
IdCiu INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomCiu NVARCHAR(50) NOT NULL,
CP INT NOT NULL
);

--Creamos la Tabla con Atractivos Turisticos
CREATE TABLE Atractivos (
IdAt INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomAt NVARCHAR(50) NOT NULL,
DescrAt NVARCHAR(300),
IdCiuAt INT,
constraint fkCiuAt foreign key(IdCiuAt) references Ciudades(IdCiu)
);

--Creamos la Tabla de RegistroClimatico
CREATE TABLE RegClima(
IdRegClima INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuReg INT,
FechaReg DATETIME,
TempMax SMALLINT,
TempMin SMALLINT,
Estado VARCHAR(20),
VientoMax INT,
constraint fkCiuReg foreign key(IdCiuReg) references Ciudades(IdCiu)
);

--Creamos la Tabla Tipo de Servicio
CREATE TABLE TipoServ(
IdTipoServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TipoS varchar(50)
);

--Creamos la Tabla Servicios
CREATE TABLE Servicios(
IdServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuS INT,
NomServ nvarchar(50),
DescrS varchar(200),
IdTipoServ INT,
TelS bigint,
emailS nvarchar(50),
constraint fkCiuS foreign key(IdCiuS) references Ciudades(IdCiu),
constraint fkTServS foreign key(IdTipoServ) references TipoServ(IdTipoServ)
);

--Creamos la Tabla Fotos de Servicios
CREATE TABLE FotoS(
IdFotoS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoS varchar(20),
IdServFS INT,
RutaFS nvarchar(50),
constraint fkIdServFS foreign key(IdServFS) references Servicios(IdServ)
);

--Creamos la Tabla Fotos de Atractivos
CREATE TABLE FotoA(
IdFotoA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoA varchar(20),
IdAtFA INT,
RutaFA nvarchar(50),
constraint fkAtFA foreign key(IdAtFA) references Atractivos(IdAt)
);

--Creamos la Tabla Intermedia entre Usuarios y Atractivos
CREATE TABLE UsAt(
IdUsUA INT,
IdAtUA INT,
FechaUA DATETIME,
constraint fkUsUsAt foreign key(IdUsUA) references Usuarios(IdUs),
constraint fkAtUsAt foreign key(IdAtUA) references Atractivos(IdAt)
);

--Creamos la Tabla Posteos, para registrar los comentarios del foro
CREATE TABLE Posteos(
IdPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUsPo INT,
--IdTitulo INT,
--IdTema INT,
Tag varchar(30),
FechaPo DATETIME,
Comentario nvarchar(300) NOT NULL,
constraint fkUsPo foreign key(IdUsPo) references Usuarios(IdUs),
);

**Comment by saon** [comment]
Por supuesto, sería bueno que lo probaran también, por las dudas.

**Comment by javihuel** [comment]
Perfecto Oscar! Confirmado. Ahora si corre sin errores y todo de una!

**Comment by javihuel** [comment]
Agrego como clave primaria, en la tabla intermedia generada por la relación entre las tablas Usuarios y Atractivos, las dos claves foráneas existentes. Ninguna de estas claves puede ser nula.

SCRIPT DE LA BASE DE DATOS – PROYECTO VOY
/* BASE DE DATOS PROYECTO VOY - GRUPO 2A - VERSION 5
Creamos la BD */
create database BD_Voy;
GO
--La ponemos en uso
use BD_Voy;
 
--Creamos la tabla Usuarios
CREATE TABLE Usuarios (
IdUs INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Nick NVARCHAR(40) NOT NULL,
ContUs VARCHAR(40) NOT NULL,
TipoUs INT NOT NULL,
emailUs VARCHAR(20)
--constraint pk_us primary key (IdUs)
);
--Decidir como vamos manejar el tipo de usuario, un numero 1-Adm 2-Reg 0-Visitante?
 
----Creamos la tabla Ciudades
CREATE TABLE Ciudades (
IdCiu INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomCiu NVARCHAR(50) NOT NULL,
CP INT NOT NULL
);
 
--Creamos la Tabla con Atractivos Turisticos
CREATE TABLE Atractivos (
IdAt INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NomAt NVARCHAR(50) NOT NULL,
DescrAt NVARCHAR(300),
IdCiuAt INT,
constraint fkCiuAt foreign key(IdCiuAt) references Ciudades(IdCiu)
);
 
--Creamos la Tabla de RegistroClimatico
CREATE TABLE RegClima(
IdRegClima INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuReg INT,
FechaReg DATETIME,
TempMax SMALLINT,
TempMin SMALLINT,
Estado VARCHAR(20),
VientoMax INT,
constraint fkCiuReg foreign key(IdCiuReg) references Ciudades(IdCiu)
);
 
--Creamos la Tabla Tipo de Servicio
CREATE TABLE TipoServ(
IdTipoServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TipoS varchar(50)
);
 
--Creamos la Tabla Servicios
CREATE TABLE Servicios(
IdServ INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCiuS INT,
NomServ nvarchar(50),
DescrS varchar(200),
IdTipoServ INT,
TelS bigint,
emailS nvarchar(50),
constraint fkCiuS foreign key(IdCiuS) references Ciudades(IdCiu),
constraint fkTServS foreign key(IdTipoServ) references TipoServ(IdTipoServ)
);
 
--Creamos la Tabla Fotos de Servicios
CREATE TABLE FotoS(
IdFotoS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoS varchar(20),
IdServFS INT,
RutaFS nvarchar(50),
constraint fkIdServFS foreign key(IdServFS) references Servicios(IdServ)
);
 
--Creamos la Tabla Fotos de Atractivos
CREATE TABLE FotoA(
IdFotoA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomFotoA varchar(20),
IdAtFA INT,
RutaFA nvarchar(50),
constraint fkAtFA foreign key(IdAtFA) references Atractivos(IdAt)
);
 
 
--Creamos la Tabla Intermedia entre Usuarios y Atractivos
CREATE TABLE UsAt(
IdUsUA INT NOT NULL,
IdAtUA INT NOT NULL,
FechaUA DATETIME,
primary key (IdUsUA, IdAtUA),
constraint fkUsUsAt foreign key(IdUsUA) references Usuarios(IdUs),
constraint fkAtUsAt foreign key(IdAtUA) references Atractivos(IdAt)
);
 
 
--Creamos la Tabla Posteos, para registrar los comentarios del foro
CREATE TABLE Posteos(
IdPost INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUsPo INT,
--IdTitulo INT,
--IdTema INT,
Tag varchar(30),
FechaPo DATETIME,
Comentario nvarchar(300) NOT NULL,
constraint fkUsPo foreign key(IdUsPo) references Usuarios(IdUs),
);
