### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by IanCarab** [classroomEntreRios/proyecto-g2a-proyecto-g2a#5]
Como usuario visitante
quiero seleccionar una localidad
para ver los atractivos turísticos de esta

Como usuario visitante quiero
seleccionar una localidad
para ver el clima de los siguientes 3 días

Como usuario visitante quiero
ver el clima en la capital provincial
para que no sea necesario seleccionar una ciudad antes de decidir su visita

Como usuario visitante quiero
tener acceso a un chat
para comunicarme con otros visitantes

Como usuario visitante quiero
seleccionar un atractivo turístico
para obtener información sobre este

Como usuario visitante quiero
seleccionar una localidad
para obtener información sobre los servicios turísticos ofrecidos

Como usuario visitante quiero
darme de alta en el sistema
para ser un usuario registrado

Como usuario registrado quiero
acceder a mi perfil
para modificar mis datos

Como usuario registrado quiero
acceder al foro para
leer/escribir comentarios sobre visitas

Como usuario registrado quiero
acceder al foro y seleccionar una etiqueta para
crear un posteo o buscar posteos con esa etiqueta

Como usuario registrado quiero
editar mis comentarios
para eliminar o modificar mis comentarios en el foro

Como usuario registrado quiero
seleccionar dos fechas para
visualizar información sobre el historial del clima entre las fechas seleccionadas

Como usuario administrador quiero
crear etiquetas en el foro
para que los usuarios registrados puedan agregar comentarios en diferentes grupos (#pesca,#termas,etc)

Como usuario administrador quiero
borrar comentarios del foro
para que no haya comentarios inadecuados

Como usuario administrador quiero
acceder a la base de datos para
consultar la información referida a un atractivo turístico

Como usuario administrador quiero
acceder a la base de datos para
modificar/actualizar la información referida a un atractivo turístico

Como usuario administrador quiero
acceder a la base de datos para
eliminar la información referida a un atractivo turístico

Como usuario administrador quiero
acceder a la base de datos para
dar de alta información referida a a los servicios ofrecidos por una ciudad

Como usuario administrador quiero
acceder a la base de datos para
consultar la informacion referida a los servicios ofrecidos por una ciudad

Como usuario administrador quiero
acceder a la base de datos para
modificar la información referida a los servicios ofrecidos por una ciudad

Como usuario administrador quiero
acceder a la base de datos para
eliminar la información referida a los servicios ofrecidos por una ciudad

**Comment by FernandoStreet** [comment]
Como usuario administrador
quiero saber
que atractivos turísticos fue mas visitado en la pagina
